# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            emuelu
tagline:          'sustainable knit and crochet'
description:      'sustainable knit and crochet'
url:              http://emuelu.com
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
