# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            emuelu
tagline:          'sustainable knit and crochet'
description:      'sustainable knit and crochet'
url:              
baseurl:          http://www.ravelry.com/people/emuelu

author:
  name:           ''
  url:            

patterns.url: http://www.ravelry.com/people/emuelu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:
